In [1]:
import numpy as np
import polars as pl 

In [2]:
df = pl.read_csv('../data/02_sample.txt', has_header=False, separator=' ')
df

shape: (6, 5)
┌──────────┬──────────┬──────────┬──────────┬──────────┐
│ column_1 ┆ column_2 ┆ column_3 ┆ column_4 ┆ column_5 │
│ ---      ┆ ---      ┆ ---      ┆ ---      ┆ ---      │
│ i64      ┆ i64      ┆ i64      ┆ i64      ┆ i64      │
╞══════════╪══════════╪══════════╪══════════╪══════════╡
│ 7        ┆ 6        ┆ 4        ┆ 2        ┆ 1        │
│ 1        ┆ 2        ┆ 7        ┆ 8        ┆ 9        │
│ 9        ┆ 7        ┆ 6        ┆ 2        ┆ 1        │
│ 1        ┆ 3        ┆ 2        ┆ 4        ┆ 5        │
│ 8        ┆ 6        ┆ 4        ┆ 4        ┆ 1        │
│ 1        ┆ 3        ┆ 6        ┆ 7        ┆ 9        │
└──────────┴──────────┴──────────┴──────────┴──────────┘

In [3]:
df_np = df.to_numpy()


In [4]:
#https://stackoverflow.com/questions/30734258/efficiently-check-if-numpy-ndarray-values-are-strictly-increasing
np.diff(df_np[0]) > 0

array([False, False, False, False])

In [5]:
np.all(df_np[:, 1:] >= df_np[:, :-1], axis=1)


array([False,  True, False, False, False,  True])

In [6]:
df_np[0]

array([7, 6, 4, 2, 1])

In [7]:
np.all(np.diff(df_np) > 0) | np.all(np.diff(df_np) < 0)

False

In [8]:
condition = (np.all(np.diff(df_np, axis=1) > 0, axis=1) | np.all(np.diff(df_np, axis=1) < 0, axis=1))
filtered_rows = df_np[condition]
filtered_rows

array([[7, 6, 4, 2, 1],
       [1, 2, 7, 8, 9],
       [9, 7, 6, 2, 1],
       [1, 3, 6, 7, 9]])